<Project>
  <!-- Temporarily disabled to fix duplicate assembly info errors -->
  <!--
  <PropertyGroup Condition="'$(EA_BUILD_ROOT)' != ''">
    <BaseOutputPath>$(EA_BUILD_ROOT)\bin\$(MSBuildProjectName)\</BaseOutputPath>
    <BaseIntermediateOutputPath>$(EA_BUILD_ROOT)\obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
  </PropertyGroup>
  -->
</Project>

