// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eBayHero.Infrastructure.Data;

#nullable disable

namespace eBayHero.Infrastructure.Data.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    partial class InventoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.28");

            modelBuilder.Entity("eBayHero.Core.Models.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("eBayHero.Core.Models.AuditEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DestinationPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Exception")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedUtc");

                    b.ToTable("AuditEvents");
                });

            modelBuilder.Entity("eBayHero.Core.Models.CustomFieldValue", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InventoryItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId", "FieldName")
                        .IsUnique();

                    b.ToTable("CustomFieldValues");
                });

            modelBuilder.Entity("eBayHero.Core.Models.EbayConnectionProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilitiesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientIdHint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectedAccountDisplay")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Environment")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MarketplaceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("PublishingEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("RefreshTokenExpiresUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RuName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScopeList")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TokenExpiresUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Environment");

                    b.ToTable("EbayConnectionProfiles");
                });

            modelBuilder.Entity("eBayHero.Core.Models.ExportItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExportPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExportRunId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InventoryItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhotoId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PhotoOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExportRunId");

                    b.ToTable("ExportItems");
                });

            modelBuilder.Entity("eBayHero.Core.Models.ExportRun", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExportRoot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ManifestCsvPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ManifestJsonPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PhotoCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ExportRuns");
                });

            modelBuilder.Entity("eBayHero.Core.Models.FileOperation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CompletedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DestinationPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhotoId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReversalDestinationPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReversalSourcePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("FileOperations");
                });

            modelBuilder.Entity("eBayHero.Core.Models.ImageEditOperation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageEditSessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InputPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutputPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UndoPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImageEditSessionId");

                    b.ToTable("ImageEditOperations");
                });

            modelBuilder.Entity("eBayHero.Core.Models.ImageEditSession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentDerivedPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentOperationIndex")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ModifiedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OverwriteOriginalApproved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhotoId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PhotoId");

                    b.ToTable("ImageEditSessions");
                });

            modelBuilder.Entity("eBayHero.Core.Models.InventoryItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Autograph")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DateListedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DateSoldUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GradingCompany")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ListingId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ListingPlatform")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ListingStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ListingUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ModifiedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerOrTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Relic")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Rookie")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("SalePrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SetName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SportOrGame")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DateListedUtc");

                    b.HasIndex("ListingStatus");

                    b.HasIndex("Name");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("eBayHero.Core.Models.ItemTag", b =>
                {
                    b.Property<string>("InventoryItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TagId")
                        .HasColumnType("TEXT");

                    b.HasKey("InventoryItemId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ItemTags");
                });

            modelBuilder.Entity("eBayHero.Core.Models.Job", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentFile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("EndedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorDetails")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Progress")
                        .HasColumnType("REAL");

                    b.Property<long?>("StartedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Kind");

                    b.HasIndex("Status");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("eBayHero.Core.Models.JobAttempt", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("EndedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorDetails")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("JobAttempts");
                });

            modelBuilder.Entity("eBayHero.Core.Models.ListingAuditFinding", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AfterJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Approved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BeforeJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FixSafety")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MarketplaceListingId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Resolved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MarketplaceListingId");

                    b.ToTable("ListingAuditFindings");
                });

            modelBuilder.Entity("eBayHero.Core.Models.MarketplaceListing", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("BestOfferEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BuyItNowEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConditionDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalListingId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FulfillmentPolicyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HandlingTimeDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InventoryItemId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAuction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemSpecificsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Marketplace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ModifiedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentPolicyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PublishingEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReturnPolicyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SaleLotId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ScheduledUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("ModifiedUtc");

                    b.HasIndex("SaleLotId");

                    b.HasIndex("Status");

                    b.ToTable("MarketplaceListings");
                });

            modelBuilder.Entity("eBayHero.Core.Models.MarketplaceListingPhoto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketplaceListingId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ViewType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MarketplaceListingId");

                    b.HasIndex("PhotoId");

                    b.ToTable("MarketplaceListingPhotos");
                });

            modelBuilder.Entity("eBayHero.Core.Models.OcrCandidate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double>("AverageConfidence")
                        .HasColumnType("REAL");

                    b.Property<double>("CandidateScore")
                        .HasColumnType("REAL");

                    b.Property<string>("Crop")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CropRectangleJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DerivedImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorOutput")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ExecutionMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OcrRunId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PageSegmentationMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreprocessingProfile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RawTsv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecognizedText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("RotationDegrees")
                        .HasColumnType("REAL");

                    b.Property<string>("TransformMatrixJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WordBoxesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("WordConfidence")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("OcrRunId");

                    b.ToTable("OcrCandidates");
                });

            modelBuilder.Entity("eBayHero.Core.Models.OcrCorrection", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectedText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IncorrectText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("LastUsedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsageCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Field", "IncorrectText");

                    b.ToTable("OcrCorrections");
                });

            modelBuilder.Entity("eBayHero.Core.Models.OcrImageArtifact", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CropRectangleJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DerivedImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OcrRunId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreprocessingProfile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("RotationDegrees")
                        .HasColumnType("REAL");

                    b.Property<string>("TransformMatrixJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OcrRunId");

                    b.HasIndex("PhotoId");

                    b.ToTable("OcrImageArtifacts");
                });

            modelBuilder.Entity("eBayHero.Core.Models.OcrReview", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectedMetadataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectedText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Learned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OcrRunId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ReviewedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectedCandidateId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OcrRunId");

                    b.HasIndex("PhotoId");

                    b.ToTable("OcrReviews");
                });

            modelBuilder.Entity("eBayHero.Core.Models.OcrRun", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double>("AverageConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("BestText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CompletedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorOutput")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ExecutionMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhotoId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Profile")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartedUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PhotoId");

                    b.ToTable("OcrRuns");
                });

            modelBuilder.Entity("eBayHero.Core.Models.OcrVocabulary", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Word")
                        .IsUnique();

                    b.ToTable("OcrVocabularies");
                });

            modelBuilder.Entity("eBayHero.Core.Models.Photo", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ImportedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDuplicate")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMissing")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ModifiedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("OcrConfidence")
                        .HasColumnType("REAL");

                    b.Property<int>("OcrProfile")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OcrReviewed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OcrText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("PerceptualHash")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ViewType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FullPath");

                    b.HasIndex("ImportedUtc");

                    b.HasIndex("Sha256");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("eBayHero.Core.Models.PhotoItemLink", b =>
                {
                    b.Property<string>("PhotoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("InventoryItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageRoleCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ViewType")
                        .HasColumnType("INTEGER");

                    b.HasKey("PhotoId", "InventoryItemId");

                    b.HasIndex("InventoryItemId");

                    b.ToTable("PhotoItemLinks");
                });

            modelBuilder.Entity("eBayHero.Core.Models.PhotoTag", b =>
                {
                    b.Property<string>("PhotoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TagId")
                        .HasColumnType("TEXT");

                    b.HasKey("PhotoId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("PhotoTags");
                });

            modelBuilder.Entity("eBayHero.Core.Models.PriceEvidence", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Fees")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Included")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InventoryItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOutlier")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ObservedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Shipping")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId");

                    b.ToTable("PriceEvidence");
                });

            modelBuilder.Entity("eBayHero.Core.Models.PriceSnapshot", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AuctionStart")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Average")
                        .HasColumnType("TEXT");

                    b.Property<int>("ComparableCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Confidence")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EstimatedFees")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EstimatedNet")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("High")
                        .HasColumnType("TEXT");

                    b.Property<string>("InventoryItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Low")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MarketPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Median")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NeedsResearch")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PremiumPrice")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PriceLocked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProvenanceJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("QuickSalePrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Shipping")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TrimmedAverage")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId");

                    b.ToTable("PriceSnapshots");
                });

            modelBuilder.Entity("eBayHero.Core.Models.SaleLot", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EstimatedFees")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EstimatedIndividualValue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EstimatedNet")
                        .HasColumnType("TEXT");

                    b.Property<long>("ModifiedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Shipping")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SuggestedAuctionStart")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SuggestedBuyItNow")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SuggestedLotValue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("WeightOunces")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SaleLots");
                });

            modelBuilder.Entity("eBayHero.Core.Models.SaleLotItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ExplicitlyAllowedInMultipleActiveLots")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InventoryItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SaleLotId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("SaleLotId");

                    b.ToTable("SaleLotItems");
                });

            modelBuilder.Entity("eBayHero.Core.Models.SavedView", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ColumnLayoutJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilterJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ModifiedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("SavedViews");
                });

            modelBuilder.Entity("eBayHero.Core.Models.SourceRoot", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("CopyIntoManagedStorage")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExcludePatterns")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IncludePatterns")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IndexInPlace")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastScanUtc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MoveIntoManagedStorage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Recursive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WatchForChanges")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Path");

                    b.ToTable("SourceRoots");
                });

            modelBuilder.Entity("eBayHero.Core.Models.Tag", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("eBayHero.Core.Models.CustomFieldValue", b =>
                {
                    b.HasOne("eBayHero.Core.Models.InventoryItem", "InventoryItem")
                        .WithMany("CustomFields")
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("eBayHero.Core.Models.ExportItem", b =>
                {
                    b.HasOne("eBayHero.Core.Models.ExportRun", "ExportRun")
                        .WithMany("Items")
                        .HasForeignKey("ExportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExportRun");
                });

            modelBuilder.Entity("eBayHero.Core.Models.ImageEditOperation", b =>
                {
                    b.HasOne("eBayHero.Core.Models.ImageEditSession", "ImageEditSession")
                        .WithMany("Operations")
                        .HasForeignKey("ImageEditSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImageEditSession");
                });

            modelBuilder.Entity("eBayHero.Core.Models.ImageEditSession", b =>
                {
                    b.HasOne("eBayHero.Core.Models.Photo", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("eBayHero.Core.Models.ItemTag", b =>
                {
                    b.HasOne("eBayHero.Core.Models.InventoryItem", "InventoryItem")
                        .WithMany("ItemTags")
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eBayHero.Core.Models.Tag", "Tag")
                        .WithMany("ItemTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("eBayHero.Core.Models.JobAttempt", b =>
                {
                    b.HasOne("eBayHero.Core.Models.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("eBayHero.Core.Models.ListingAuditFinding", b =>
                {
                    b.HasOne("eBayHero.Core.Models.MarketplaceListing", "MarketplaceListing")
                        .WithMany("AuditFindings")
                        .HasForeignKey("MarketplaceListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarketplaceListing");
                });

            modelBuilder.Entity("eBayHero.Core.Models.MarketplaceListing", b =>
                {
                    b.HasOne("eBayHero.Core.Models.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("eBayHero.Core.Models.SaleLot", "SaleLot")
                        .WithMany()
                        .HasForeignKey("SaleLotId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("InventoryItem");

                    b.Navigation("SaleLot");
                });

            modelBuilder.Entity("eBayHero.Core.Models.MarketplaceListingPhoto", b =>
                {
                    b.HasOne("eBayHero.Core.Models.MarketplaceListing", "MarketplaceListing")
                        .WithMany("Photos")
                        .HasForeignKey("MarketplaceListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eBayHero.Core.Models.Photo", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarketplaceListing");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("eBayHero.Core.Models.OcrCandidate", b =>
                {
                    b.HasOne("eBayHero.Core.Models.OcrRun", "OcrRun")
                        .WithMany("Candidates")
                        .HasForeignKey("OcrRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OcrRun");
                });

            modelBuilder.Entity("eBayHero.Core.Models.OcrImageArtifact", b =>
                {
                    b.HasOne("eBayHero.Core.Models.OcrRun", "OcrRun")
                        .WithMany()
                        .HasForeignKey("OcrRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eBayHero.Core.Models.Photo", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OcrRun");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("eBayHero.Core.Models.OcrReview", b =>
                {
                    b.HasOne("eBayHero.Core.Models.OcrRun", "OcrRun")
                        .WithMany()
                        .HasForeignKey("OcrRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eBayHero.Core.Models.Photo", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OcrRun");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("eBayHero.Core.Models.OcrRun", b =>
                {
                    b.HasOne("eBayHero.Core.Models.Photo", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("eBayHero.Core.Models.PhotoItemLink", b =>
                {
                    b.HasOne("eBayHero.Core.Models.InventoryItem", "InventoryItem")
                        .WithMany("PhotoLinks")
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eBayHero.Core.Models.Photo", "Photo")
                        .WithMany("ItemLinks")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("eBayHero.Core.Models.PhotoTag", b =>
                {
                    b.HasOne("eBayHero.Core.Models.Photo", "Photo")
                        .WithMany("PhotoTags")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eBayHero.Core.Models.Tag", "Tag")
                        .WithMany("PhotoTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("eBayHero.Core.Models.PriceEvidence", b =>
                {
                    b.HasOne("eBayHero.Core.Models.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("eBayHero.Core.Models.PriceSnapshot", b =>
                {
                    b.HasOne("eBayHero.Core.Models.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("eBayHero.Core.Models.SaleLotItem", b =>
                {
                    b.HasOne("eBayHero.Core.Models.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eBayHero.Core.Models.SaleLot", "SaleLot")
                        .WithMany("Items")
                        .HasForeignKey("SaleLotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");

                    b.Navigation("SaleLot");
                });

            modelBuilder.Entity("eBayHero.Core.Models.ExportRun", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("eBayHero.Core.Models.ImageEditSession", b =>
                {
                    b.Navigation("Operations");
                });

            modelBuilder.Entity("eBayHero.Core.Models.InventoryItem", b =>
                {
                    b.Navigation("CustomFields");

                    b.Navigation("ItemTags");

                    b.Navigation("PhotoLinks");
                });

            modelBuilder.Entity("eBayHero.Core.Models.MarketplaceListing", b =>
                {
                    b.Navigation("AuditFindings");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("eBayHero.Core.Models.OcrRun", b =>
                {
                    b.Navigation("Candidates");
                });

            modelBuilder.Entity("eBayHero.Core.Models.Photo", b =>
                {
                    b.Navigation("ItemLinks");

                    b.Navigation("PhotoTags");
                });

            modelBuilder.Entity("eBayHero.Core.Models.SaleLot", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("eBayHero.Core.Models.Tag", b =>
                {
                    b.Navigation("ItemTags");

                    b.Navigation("PhotoTags");
                });
#pragma warning restore 612, 618
        }
    }
}
