<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\eBayHero.Core\eBayHero.Core.csproj" />
    <ProjectReference Include="..\..\src\eBayHero.Infrastructure\eBayHero.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\eBayHero.FileSystem\eBayHero.FileSystem.csproj" />
    <ProjectReference Include="..\..\src\eBayHero.Ocr\eBayHero.Ocr.csproj" />
    <ProjectReference Include="..\..\src\eBayHero.Export\eBayHero.Export.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.20">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>

